version: '2'
services:
    libsupport-app:
        image: libsupport
        external_links:
            - libsupport-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/LibSupport
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    libsupport-postgresql:
        extends:
            file: postgresql.yml
            service: libsupport-postgresql
